### Project that we will compile:
CONTIKI_PROJECT = zol29

all: $(CONTIKI_PROJECT)
TARGET = zoul
CONTIKI = ../../../contiki
include $(CONTIKI)/Makefile.include
CONTIKI_TARGET_SOURCEFILES +=  adc-zoul.c
